### ISSUE TITLE
Repo - Write a proper Readme

### ISSUE THREAD

**Issue by WerWolv** [SteamDeckHomebrew/decky-playground#1]
The repo's currently lacking some documentation in form of a Readme.

**Comment by DanBurkhardt** [comment]
+100 need readme with full build / run / install instructions

**Comment by TrainDoctor** [comment]
Repo is largely unmaintained. Not a relevant need.

**Comment by DanBurkhardt** [comment]
No worries, this project isn't really a good use of time anyway-- these unofficial solutions are going to be wiped out over and over by steamOS changes and eventually valve will just support a category of apps to extend the OS.

**Comment by TrainDoctor** [comment]
> No worries, this project isn't really a good use of time anyway-- these unofficial solutions are going to be wiped out over and over by steamOS changes and eventually valve will just support a category of apps to extend the OS.

I'd be very interested to know where you get the information to back up such a claim. Regardless Decky and it's associated tools + repositories will continue to be maintained so long as there is user demand.
